# non-minecraft values
org.gradle.jvmargs=-Xmx6096M
jetbrainsAnnotationsVersion=23.0.0

# gradle kotlin jvm plugin breaks without this
kotlin.stdlib.default.dependency=false

mavenGroup=com.meepoffaith.hextrapats
modId=hextrapats
modVersion=1.9.0
previewVersion=3

# game version for hexdoc
minecraftVersion=1.21.1

# publishing (TODO: fill these in!)
curseforgeId=
modrinthId=
